#this code CONFIGURES the serverless functions
#information about the code goes here 

service: auth-server

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 30 # optional, in seconds, default is 6

# this is to specify the values of the key & secret
 
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL # this points to getAuthURL in the handler.js file. Anytime getAuthURL is called, lambda runs this handler
# specifies which events will triger the getAuthURL to be invoked
    events:
      - http:
          path: api/get-auth-url
          method: get

  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http: 
          path: api/get-events/{access_token}
          method: get
